# Template Terraform to deploy to Cloud Infrastructure

# This template allows you to deploy your infrastructure using Terraform to supported cloud providers.
# The workflow allows running tests, security scans on feature branches (as well as master).
# After merging code to master the infrastructure will be deployed to cloud according to the given terraform template.

# Prerequisites: credentials according to used cloud provider.
# For advanced cases, please, follow terraform docs https://www.terraform.io/docs/index.html.

pipelines:
  default:
    - parallel:
        - step:
            name: Validate
            image: hashicorp/terraform
            script:
               - terraform fmt -recursive -check

        - step:
            name: Validate
            image: ubuntu:latest
            trigger: manual
            script:
               - wget "https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip" -O tflint.zip
               - unzip tflint.zip && mv tflint /usr/local/bin/ && tflint --version
               - tflint --recursive --config "$(pwd)/.tflint.hcl"

        - step:
            name: Validate
            image: bridgecrew/checkov:latest
            trigger: manual
            script:
              - wget "https://github.com/liamg/tfsec/releases/latest/download/tfsec-linux-amd64" -O tfsec
              - chmod +x tfsec && mv tfsec /usr/local/bin/ && tfsec --version
              - tfsec .

        - step:
            name: Security Scan
            script:
              - pipe: atlassian/git-secrets-scan:0.5.1

  branches:
    master:
      - step:
          oidc: true
          image: amazon/aws-cli
          max-time: 5
          script:
            - aws sts assume-role-with-web-identity
              --role-arn $IODC_IAM_ROLE_ARN
              --role-session-name bitbucket-build-session
              --web-identity-token "$BITBUCKET_STEP_OIDC_TOKEN"
              --duration-seconds 1000

      - step:
          name: Validate
          image: hashicorp/terraform
          script:
              - terraform init --upgrade

      - step:
          name: Deploy to Production
          deployment: Production
          image: hashicorp/terraform
          trigger: manual
          script:
            - terraform init
            - terraform plan
          #  - terraform apply -auto-approve
