---
name: oidc

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  caller-identity:
    name: check caller identity
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
      - name: Configure AWS master credentials
        uses: aws-actions/configure-aws-credentials@v4
        id: master_iodc_creds
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.MASTER_IODC_ROLE_ARN }}
          output-credentials: true
      - name: get caller identity
        run: |
          aws sts get-caller-identity
          aws s3 ls

      - name: Configure AWS devepment credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ steps.master_iodc_creds.outputs.aws-access-key-id }}
          aws-secret-access-key: ${{ steps.master_iodc_creds.outputs.aws-secret-access-key }}
          aws-session-token: ${{ steps.master_iodc_creds.outputs.aws-session-token }}
          role-to-assume: ${{ secrets.TERRAFORM_DEVELOP_ROLE_ARN }}
      - name: get caller identity
        run: |
          aws sts get-caller-identity
          aws s3 ls