---
name: "Terraform CI/CD to AWS"

env:
  DIR: "."
  TF_VERSION: "1.8.0"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  caller-identity:
    name: check caller identity
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
      - name: Configure AWS master credentials
        uses: aws-actions/configure-aws-credentials@v4
        id: master_iodc_creds
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.MASTER_IODC_ROLE_ARN }}
          output-credentials: true

      - name: get caller identity
        run: |
          aws sts get-caller-identity
          aws s3 ls

      - name: Configure AWS devepment credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ steps.master_iodc_creds.outputs.aws-access-key-id }}
          aws-secret-access-key: ${{ steps.master_iodc_creds.outputs.aws-secret-access-key }}
          aws-session-token: ${{ steps.master_iodc_creds.outputs.aws-session-token }}
          role-to-assume: ${{ secrets.TERRAFORM_DEVELOP_ROLE_ARN }}

      - name: get caller identity
        run: |
          aws sts get-caller-identity
          aws s3 ls

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform format
        id: tf_fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: ssh_key
        working-directory: ${{ env.DIR }}
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          #  Copied from https://github.com/maddox/actions/blob/master/ssh/entrypoint.sh
        run: |
          SSH_PATH="$HOME/.ssh"

          mkdir -p "$SSH_PATH"
          touch "$SSH_PATH/known_hosts"

          echo "$PRIVATE_KEY" > "$SSH_PATH/id_rsa"

          chmod 700 "$SSH_PATH"
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 600 "$SSH_PATH/known_hosts"
          chmod 600 "$SSH_PATH/id_rsa"

          eval $(ssh-agent)
          ssh-add "$SSH_PATH/id_rsa"

          terraform init